### ISSUE TITLE
[Feature] List `postcss-html` as a dependency, but not dev dependency

### ISSUE THREAD

**Issue by fengyuanchen** [ota-meshi/stylelint-config-recommended-vue#13]
After implementing this, it will be easier for users to use, as they don't need to install the `postcss-html` package manually.

Just like the `stylelint-config-recommended-scss` package [list the `postcss-scss` as a dependency](https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/master/package.json#L44).

**Comment by ota-meshi** [comment]
Thank you for this issue.

But, I don't do that because it will not work for some users.

If not use peerDependency, it may not be able to handle the configuration well.
It's similar to the issue below:
https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/2
