### ISSUE TITLE
Does not lint <style lang="scss"> correctly

### ISSUE THREAD

**Issue by Snack-X** [ota-meshi/stylelint-config-recommended-vue#16]
I have no idea where should I report this (`stylelint-config-html`? `postcss-html`?), so I'm leaving it here.

After upgrading Stylelint to v14 and applying other needed changes, I've noticed `<style lang="scss">` block in `.vue` file does not get linted properly.

Below is my minimal reproduction:

---

**package.json**

```json
{
  "devDependencies": {
    "postcss-html": "^1.3.0",
    "stylelint": "^14.1.0",
    "stylelint-config-recommended-vue": "^1.0.0",
    "stylelint-config-standard-scss": "^3.0.0"
  }
}
```

**.stylelintrc**

```json
{
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-recommended-vue",
  ]
}
```

**test.scss**

```scss
@mixin test {
  padding: 1px 1px
}

.selector {
  @include mixin
}
```

**test.vue**

```vue
<style lang="scss">
@mixin test {
  padding: 1px 1px
}

.selector {
  @include mixin
}
</style>
```

---

Running `./node_modules/.bin/stylelint *.{scss,vue}` results below:

```
$ ./node_modules/.bin/stylelint *.{scss,vue}

test.scss
 2:3   ✖  Unexpected longhand value '1px 1px' instead of '1px'  shorthand-property-no-redundant-values
 2:18  ✖  Expected a trailing semicolon                         declaration-block-trailing-semicolon
 6:16  ✖  Expected a trailing semicolon                         declaration-block-trailing-semicolon
 6:17  ✖  Expected newline before "}" of a multi-line block     block-closing-brace-newline-before

test.vue
 2:1   ✖  Unexpected unknown at-rule "@mixin"                   at-rule-no-unknown
 3:3   ✖  Unexpected longhand value '1px 1px' instead of '1px'  shorthand-property-no-redundant-values
 3:18  ✖  Expected a trailing semicolon                         declaration-block-trailing-semicolon
 7:3   ✖  Unexpected unknown at-rule "@include"                 at-rule-no-unknown
 7:16  ✖  Expected a trailing semicolon                         declaration-block-trailing-semicolon
 7:17  ✖  Expected newline before "}" of a multi-line block     block-closing-brace-newline-before
```

4 errors on `test.scss` are pretty much expected, and 4 out of 6 errors on `test.vue` are also the same.
But remaining two errors should not happen. `@mixin` and `@include` are both valid at-rules on Sass/SCSS.

I think `lang` attribute on `<style>` block does not get recognized, and treated as plain CSS, or something. I don't know.

Although applying fixes from stylelint-scss/stylelint-config-standard-scss#6 does solve the issue, this should be fixed at somewhere.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

stylelint-config-recommended-vue and stylelint-config-standard-scss are not compatible.
stylelint-config-recommended-vue overwrites some of the rules of the stylelint-config-standard-scss configuration. Also, stylelint-config-standard-scss overwrites some of the rules of the stylelint-config-recommended-vue configuration.

I think someone needs to release a shareable configuration for using vue and scss together.

Currently it doesn't exist, so I think you need to configure it as follows:

```json
{
  "extends": [
    "stylelint-config-standard-scss"
  ],
  "overrides": [
        {
            "files": ["*.vue", "**/*.vue"],
            "extends": ["stylelint-config-standard-scss", "stylelint-config-html"],
            "rules": {
                "selector-pseudo-class-no-unknown": [
                    true,
                    {
                        "ignorePseudoClasses": ["deep", "global"]
                    }
                ],
                "selector-pseudo-element-no-unknown": [
                    true,
                    {
                        "ignorePseudoElements": [
                            "v-deep",
                            "v-global",
                            "v-slotted"
                        ]
                    }
                ]
            }
        }
    ]
}
```
