### ISSUE TITLE
Specify Vue config should be always last in `extends` array

### ISSUE THREAD

**Issue by IlCallo** [ota-meshi/stylelint-config-recommended-vue#19]
I guess it's implicit, but I'd make explicit that the Vue config should be the last one in the "extend" array, otherwise other configs used after Vue will try to parse vue files and fail, since the applied customSyntax for them won't be the correct one.

Examples with `stylelint-config-recommended-vue/scss` are fine, but if another config extension is added (eg. `stylelint-config-sass-guidelines`) it may not be clear they must be before Vue config entry, especially since it requires the user to understand how the underlying "customSyntax" works

**Comment by ota-meshi** [comment]
Thank you for your suggestion. Can you open a PR to add that section (FAQ section?) to the README?
