### ISSUE TITLE
Add `v-bind`exception for `value-keyword-case` into Vue rules

### ISSUE THREAD

**Issue by IlCallo** [ota-meshi/stylelint-config-recommended-vue#20]
Currently `v-bind` usage into SFCs (introduced with Vue3) is marked with a warning due to `value-keyword-case` default option set by `stylelint-config-standard` ruleset

I'd add
```json
        "value-keyword-case": [
          "lower",
          {
            "ignoreFunctions": ["v-bind"]
          }
        ]
```

Into the custom rules from this package to avoid headaches to devs using that feature and this config extension

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
I think we need a new package stylelint-config-standard-vue.
This is because stylelint-config-recommended-vue is an extension of stylelint-config-recommended and I don't think it should include stylistic rules.

**Comment by ota-meshi** [comment]
I have released a new package.
https://www.npmjs.com/package/stylelint-config-standard-vue

**Comment by IlCallo** [comment]
The newly created package only applies `stylelint-config-standard-scss` to Vue files, anyone who want out of the box support for `v-bind` when using `stylelint-config-standard-scss`, but apply additional scss ruleset (eg. `stylelint-config-sass-guidelines`, Prettier one, etc) will get just `stylelint-config-standard-scss` rules applied instead

In those cases, a solution would be to redefine the whole override `extends` array, but this would make the package pretty much useless

```json
{
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-sass-guidelines",
    "stylelint-config-standard-vue/scss"
  ],
  "overrides": [
    {
      "files": ["*.vue", "**/*.vue"],
      "extends": [
        "stylelint-config-standard-scss",
        "stylelint-config-sass-guidelines",
        "stylelint-config-recommended-vue/scss"
      ]
    }
  ]
}
```

On the other hand, if `stylelint-config-standard-vue/scss` would apply the standard rules globally

```js
{
  extends: "stylelint-config-standard-scss",
  overrides: [
        {
            files: ["*.vue", "**/*.vue"],
            extends: "stylelint-config-recommended-vue/scss",
            rules: require("../lib/vue-specific-rules"),
        },
    ],
}
```

You'd get a chicken&egg problem, as you need to put `stylelint-config-standard-vue/scss` last to get `customSyntax` working right, while you need to put other scss rulesets after it to have them applied correctly.

Pretty sure this scenario can't be solved and the solution is to create a custom configuration instead of using `stylelint-config-standard-vue/scss`, I'm just reporting it here for who'll end up in the same situation in the future
