### ISSUE TITLE
Stylelint cannot see inline ignore comments inside Vue template 

### ISSUE THREAD

**Issue by ESKempken** [ota-meshi/stylelint-config-recommended-vue#30]
Stylelint cannot see inline ignore comments inside Vue template.   
![1](https://user-images.githubusercontent.com/72070794/160081112-f2cac30e-f0f5-49f1-940e-c2cc5e610e0f.png)  

Still works fine within style tags.
![2](https://user-images.githubusercontent.com/72070794/160081113-8d6a7678-56f0-4218-a489-3de07050bd31.png)

My stylelint extends 'stylelint-config-recommended-vue' as well as 'stylelint-config-prettier'.

**Comment by ota-meshi** [comment]
Thank you for posting issue.
I think you can use `<!-- postcss-ignore -->` instead.

https://github.com/ota-meshi/postcss-html#turning-postcss-off-from-within-your-html

Note that you can't catch parsing errors when using it.
