### ISSUE TITLE
can i disabled rule for different vue lang ?

### ISSUE THREAD

**Issue by baixiaoyu2997** [ota-meshi/stylelint-config-recommended-vue#32]
I want to migrate my code incrementally  form `scss` to `postcss` ,   i want use rule only for `lang="postcss"`:
```
"overrides": [
    {
      "files": ["**/*.css","**/*.vue"],
      "rules": {
        "selector-nested-pattern": "^&"
      }
    }
  ],
```

but in `lang="scss"` sfc will warn , how to specify rules for different lang ?

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
Currently, it is not possible to change the rule config to be applied for each specified `lang`.
