### ISSUE TITLE
Unknown word (CssSyntaxError)Stylelint(CssSyntaxError)

### ISSUE THREAD

**Issue by Chen-913** [ota-meshi/stylelint-config-recommended-vue#40]
I configured stylelint according to the document, but this type of prompt error still appears on one computer. What is the reason?

```js
"postcss": "^8.4.14",
"postcss-html": "^1.5.0",
"postcss-less": "^6.0.0",
"stylelint": "^14.9.1",
"stylelint-config-recommended-vue": "^1.4.0",
"stylelint-config-recess-order": "^3.0.0",
```

"Stylelint" plug-in version：1.2.3

stylelint.config.js
```js
module.exports = {
  root: true,
  extends: [
    'stylelint-config-standard',
    // 规范 css 属性的书写顺序
    'stylelint-config-recess-order',
    'stylelint-config-recommended-vue',
  ],
  overrides: [
    {
      // less 的语法解析器
      files: '**/*.less',
      customSyntax: 'postcss-less',
    },
    {
      // 结合 stylelint-config-recommended-vue 修复在 .vue 中无法识别模板的报错
      files: '**/*.vue',
      customSyntax: 'postcss-html',
    },
  ],
  rules: {
    // 两个空格的缩进
    indentation: 2,
    'at-rule-no-unknown': [
      true,
      {
        // 解决 scss 中无法识别 @mixin 和 @include 语法的问题
        ignoreAtRules: ['mixin', 'extend', 'content', 'include'],
      },
    ],
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['deep'],
      },
    ],
    // 允许使用 less 的 if 函数
    'function-no-unknown': [true, {
      ignoreFunctions: ['if'],
    }],
    // 设置 selector-class-pattern 允许做样式穿透
    'selector-class-pattern': [
      '^([a-z][a-z0-9]*)((-|__|--)[a-z0-9]+)*$',
      {
        resolveNestedSelectors: false,
      },
    ],
  },
};
```

error:
![image](https://user-images.githubusercontent.com/72293244/190290206-1080028d-e3a0-4f40-ac50-612ac2dcf683.png)

**Comment by ota-meshi** [comment]
Please share your GitHub repository for reproducing your issue.

**Comment by Chen-913** [comment]
@ota-meshi I'd love to. This is a simplified repository.
https://github.com/Chen-913/stylelint-vue-bug.git

**Comment by ota-meshi** [comment]
I can't reproduce the problem using your repository.

**Comment by Chen-913** [comment]
Well, this may be a problem with my computer

**Comment by neostfox** [comment]
> Well, this may be a problem with my computer

在vscode的配置文件中，把vue放在最后。

**Comment by Chen-913** [comment]
> 

可以具体一点吗？或者贴一份配置出来

**Comment by Chen-913** [comment]
> > Well, this may be a problem with my computer
> 
> 在vscode的配置文件中，把vue放在最后。

可以具体一点吗？或者贴一份配置出来

**Comment by neostfox** [comment]
> > > Well, this may be a problem with my computer
> > 
> > 
> > 在vscode的配置文件中，把vue放在最后。
> 
> 可以具体一点吗？或者贴一份配置出来

{
"stylelint.validate":["css","less","postcss","scss","sass","vue"]
}
建议放到.vscode/settings.json
