### ISSUE TITLE
Please update for stylelint v15

### ISSUE THREAD

**Issue by MartinX3** [ota-meshi/stylelint-config-recommended-vue#45]

**Comment by t0byman** [comment]
This was closed but no new version has been released? Or was there a different reason this was closed?

**Comment by ota-meshi** [comment]
I believe this package already supports stylelint v15. Please write details if you have any problems.

https://github.com/ota-meshi/stylelint-config-recommended-vue/blob/124e0fd369645d5871ac7c27409ca2501f403e6e/package.json#L30-L33

I closed this issue because it looked like spam.

**Comment by t0byman** [comment]
@ota-meshi Sorry, you are right. My problem was that my default formatter was set to `Vue Language Features (Volar)` instead of `Prettier - Code formatter`.

**Comment by MartinX3** [comment]
@ota-meshi I am unsure if your plugin causes the `no-extra-semicolons` deprecation warning.
I just see that it uses `stylelint-config-recommended` and since `10.0.1` it has this rule removed.

**Comment by ota-meshi** [comment]
This package does not have fixed `stylelint-config-recommended` dependency versions.
https://github.com/ota-meshi/stylelint-config-recommended-vue/blob/124e0fd369645d5871ac7c27409ca2501f403e6e/package.json#L25-L29
I think you can solve your problem by deleting node_modules and lock files and reinstalling.

**Comment by MartinX3** [comment]
Oh, thank you
Then I need to look further which package added it.
It's hard to search since just full text search the source code of my used packages revealed no entries.
Sorry for the noise.
