### ISSUE TITLE
Hope to support less 

### ISSUE THREAD

**Issue by AAAAsea** [ota-meshi/stylelint-config-recommended-vue#58]

**Comment by ota-meshi** [comment]
I think it's already supported. You just install [postcss-less](https://github.com/shellscape/postcss-less).

**Comment by AAAAsea** [comment]
> 

That worked, and I'm truly thankful for your response.

**Comment by AAAAsea** [comment]
> I think it's already supported. You just install [postcss-less](https://github.com/shellscape/postcss-less).

That worked, and I'm truly thankful for your response.
