### ISSUE TITLE
Unknown word (CssSyntaxError)

### ISSUE THREAD

**Issue by luojin315** [ota-meshi/stylelint-config-recommended-vue#76]
There are still problems after setting according to the document

**code**
Code that can reproduce the problem：https://github.com/luojin315/test-stylelint

**config**
vscode-stylelint: v1.4.0

vscode-settings.json:`
{
    "css.validate": false,
    "less.validate": false,
    "scss.validate": false,
    "stylelint.validate": [
        "vue",
    ],
}
`
**I only downloaded the official version of vscode-stylelint**

**Comment by luojin315** [comment]
![Uploading 截屏2024-08-02 16.52.32.png…]()

**Comment by ota-meshi** [comment]
It looks like your `stylelintrc` has an extra space in it.
