### ISSUE TITLE
Is the node version too high? 

### ISSUE THREAD

**Issue by 0x083X** [ota-meshi/stylelint-config-recommended-vue#79]
Is the node version too high? 
![image](https://github.com/user-attachments/assets/d574e547-482b-41f3-b340-803850022820)

the lateset stylelint-config-recommended needs node >= 18 
![image](https://github.com/user-attachments/assets/9847c381-ffeb-4a43-987c-1cada2a53d43)

**Comment by ota-meshi** [comment]
Duplicate of #68
